// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestorationBot.Database.DataContext;

#nullable disable

namespace RestorationBot.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250302140236_AddedPainReportsAndChangedBloodPressureLogic")]
    partial class AddedPainReportsAndChangedBloodPressureLogic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RestorationBot.Models.PainReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<int>("PainLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("PainReports");
                });

            modelBuilder.Entity("RestorationBot.Models.TrainingReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SportsmenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TrainingDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SportsmenId");

                    b.ToTable("TrainingReports");
                });

            modelBuilder.Entity("RestorationBot.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("RestorationStep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RestorationBot.Models.PainReport", b =>
                {
                    b.HasOne("RestorationBot.Models.User", "Author")
                        .WithMany("PainReports")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("RestorationBot.Models.TrainingReport", b =>
                {
                    b.HasOne("RestorationBot.Models.User", "Sportsmen")
                        .WithMany("TrainingReports")
                        .HasForeignKey("SportsmenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("RestorationBot.Models.DataModels.TrainingReportData", "PostTrainingReportData", b1 =>
                        {
                            b1.Property<Guid>("TrainingReportId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BloodPressure")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<double>("HeartRate")
                                .HasColumnType("double precision");

                            b1.HasKey("TrainingReportId");

                            b1.ToTable("TrainingReports");

                            b1.WithOwner()
                                .HasForeignKey("TrainingReportId");
                        });

                    b.OwnsOne("RestorationBot.Models.DataModels.TrainingReportData", "PreTrainingReportData", b1 =>
                        {
                            b1.Property<Guid>("TrainingReportId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BloodPressure")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<double>("HeartRate")
                                .HasColumnType("double precision");

                            b1.HasKey("TrainingReportId");

                            b1.ToTable("TrainingReports");

                            b1.WithOwner()
                                .HasForeignKey("TrainingReportId");
                        });

                    b.Navigation("PostTrainingReportData")
                        .IsRequired();

                    b.Navigation("PreTrainingReportData")
                        .IsRequired();

                    b.Navigation("Sportsmen");
                });

            modelBuilder.Entity("RestorationBot.Models.User", b =>
                {
                    b.Navigation("PainReports");

                    b.Navigation("TrainingReports");
                });
#pragma warning restore 612, 618
        }
    }
}
