namespace RestorationBot.Telegram.FinalStateMachine.StateStorage.Particular.Abstract.Certain;

using Base;
using OperationsConfiguration.OperationStatesProfiles.UserChangeRestoratonStep;
using States.Implementation;

public interface IUserChangeRestorationStepStateStorageService : IStateStorageService<UserChangeRestorationStepState,
    UserChangeRestorationStepStateProfile, UserChangeRestorationStepTriggerProfile>;